### PR TITLE
View Menu with Fullscreen, Reload, and fixes placement of Check for Updates on Windows

### PR DESCRIPTION
**Pull request by ajivoin**
Addresses issues:
- #72 
- #82 

Other features:
- Adds a fullscreen toggle

I'm currently unable to test of macOS and Linux, so help with both of these would be appreciated :)

### CODE REVIEW

**Comment by chrisknepper** [comment]
Hey @ajivoin , thanks for this! I'll get this tested on Mac and Linux as soon as I can.

**Comment by chrisknepper** [comment]
Hey @ajivoin, I was able to test this and it looks good on Mac, Windows, and Ubuntu. One thing though--your code to add the fullscreen toggle--lines 8-24 of `view_menu_template.js`. It looks like Electron has implemented that and we could just use the built-in implementation by using this:

```
{
    role: 'togglefullscreen'
}
```

This also reflects the convention for the keyboard shortcut for fullscreen per-OS: F11 on Windows and Linux, and Ctrl+Cmd+F on Mac.

**Comment by ajivoin** [comment]
@chrisknepper I'll look into changing the implementation to that when I get some time to over the next few days. Thanks for testing it!

**Comment by ajivoin** [comment]
@chrisknepper Sorry for the delay, I changed both menu items in the View menu to use roles.

**Comment by chrisknepper** [comment]
@ajivoin No worries! I've also been way behind on this. I'll get a release out soon.

**Pull request merged**
