### PR TITLE
Update Electron version

### PR DESCRIPTION
**Pull request by larivierec**
There is a bug with regards to all electron applications
See link here: https://github.com/electron/electron/issues/13972

This should fix the following issue:
https://github.com/chrisknepper/android-messages-desktop/issues/100

### CODE REVIEW

**Comment by panarican** [comment]
Couldn't you set it to 2.0.12 instead of 2.0.8 I was able to build just fine with that.

**Comment by chrisknepper** [comment]
Hi @larivierec, thanks for this! I am hoping to get this pushed this weekend. Would you mind updating the version of electron in the PR to 2.0.12 as @panarican said? Could you also revert the change to the `version` field? The NPM/GitHub release updater takes care of that automatically.

**Comment by larivierec** [comment]
yeah, no problem i can do that quick!

**Comment by chrisknepper** [comment]
Wow thanks for the quick response @larivierec, I will attempt to get this one out later today.

**Pull request merged**
